/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin/withdrawals'
import { Route as AdminMarketsRouteImport } from './routes/admin/markets'
import { Route as AdminDepositsRouteImport } from './routes/admin/deposits'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyBetsRouteImport } from './routes/_authenticated/my-bets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AdminResultsHistoryRouteImport } from './routes/admin/results.history'
import { Route as AdminResultsDeclareRouteImport } from './routes/admin/results.declare'
import { Route as AdminResultsAutomationRunsRouteImport } from './routes/admin/results.automation-runs'
import { Route as AdminResultsAutomationAuditRouteImport } from './routes/admin/results.automation-audit'
import { Route as AdminResultsAutomationRouteImport } from './routes/admin/results.automation'
import { Route as AuthenticatedBetMarketIdRouteImport } from './routes/_authenticated/bet.$marketId'
import { Route as ApiPublicHooksAutoDeclareResultsRouteImport } from './routes/api/public/hooks/auto-declare-results'

const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyBetsRoute = AuthenticatedMyBetsRouteImport.update({
  id: '/my-bets',
  path: '/my-bets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminResultsHistoryRoute = AdminResultsHistoryRouteImport.update({
  id: '/results/history',
  path: '/results/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsDeclareRoute = AdminResultsDeclareRouteImport.update({
  id: '/results/declare',
  path: '/results/declare',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsAutomationRunsRoute =
  AdminResultsAutomationRunsRouteImport.update({
    id: '/results/automation-runs',
    path: '/results/automation-runs',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResultsAutomationAuditRoute =
  AdminResultsAutomationAuditRouteImport.update({
    id: '/results/automation-audit',
    path: '/results/automation-audit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResultsAutomationRoute = AdminResultsAutomationRouteImport.update({
  id: '/results/automation',
  path: '/results/automation',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedBetMarketIdRoute =
  AuthenticatedBetMarketIdRouteImport.update({
    id: '/bet/$marketId',
    path: '/bet/$marketId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksAutoDeclareResultsRoute =
  ApiPublicHooksAutoDeclareResultsRouteImport.update({
    id: '/api/public/hooks/auto-declare-results',
    path: '/api/public/hooks/auto-declare-results',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/charts': typeof ChartsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-bets': typeof AuthenticatedMyBetsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/bet/$marketId': typeof AuthenticatedBetMarketIdRoute
  '/admin/results/automation': typeof AdminResultsAutomationRoute
  '/admin/results/automation-audit': typeof AdminResultsAutomationAuditRoute
  '/admin/results/automation-runs': typeof AdminResultsAutomationRunsRoute
  '/admin/results/declare': typeof AdminResultsDeclareRoute
  '/admin/results/history': typeof AdminResultsHistoryRoute
  '/api/public/hooks/auto-declare-results': typeof ApiPublicHooksAutoDeclareResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts': typeof ChartsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-bets': typeof AuthenticatedMyBetsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
  '/bet/$marketId': typeof AuthenticatedBetMarketIdRoute
  '/admin/results/automation': typeof AdminResultsAutomationRoute
  '/admin/results/automation-audit': typeof AdminResultsAutomationAuditRoute
  '/admin/results/automation-runs': typeof AdminResultsAutomationRunsRoute
  '/admin/results/declare': typeof AdminResultsDeclareRoute
  '/admin/results/history': typeof AdminResultsHistoryRoute
  '/api/public/hooks/auto-declare-results': typeof ApiPublicHooksAutoDeclareResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/charts': typeof ChartsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-bets': typeof AuthenticatedMyBetsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/bet/$marketId': typeof AuthenticatedBetMarketIdRoute
  '/admin/results/automation': typeof AdminResultsAutomationRoute
  '/admin/results/automation-audit': typeof AdminResultsAutomationAuditRoute
  '/admin/results/automation-runs': typeof AdminResultsAutomationRunsRoute
  '/admin/results/declare': typeof AdminResultsDeclareRoute
  '/admin/results/history': typeof AdminResultsHistoryRoute
  '/api/public/hooks/auto-declare-results': typeof ApiPublicHooksAutoDeclareResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/charts'
    | '/login'
    | '/markets'
    | '/register'
    | '/results'
    | '/dashboard'
    | '/my-bets'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/markets'
    | '/admin/withdrawals'
    | '/admin/'
    | '/bet/$marketId'
    | '/admin/results/automation'
    | '/admin/results/automation-audit'
    | '/admin/results/automation-runs'
    | '/admin/results/declare'
    | '/admin/results/history'
    | '/api/public/hooks/auto-declare-results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts'
    | '/login'
    | '/markets'
    | '/register'
    | '/results'
    | '/dashboard'
    | '/my-bets'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/admin/deposits'
    | '/admin/markets'
    | '/admin/withdrawals'
    | '/admin'
    | '/bet/$marketId'
    | '/admin/results/automation'
    | '/admin/results/automation-audit'
    | '/admin/results/automation-runs'
    | '/admin/results/declare'
    | '/admin/results/history'
    | '/api/public/hooks/auto-declare-results'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/charts'
    | '/login'
    | '/markets'
    | '/register'
    | '/results'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-bets'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/admin/deposits'
    | '/admin/markets'
    | '/admin/withdrawals'
    | '/admin/'
    | '/_authenticated/bet/$marketId'
    | '/admin/results/automation'
    | '/admin/results/automation-audit'
    | '/admin/results/automation-runs'
    | '/admin/results/declare'
    | '/admin/results/history'
    | '/api/public/hooks/auto-declare-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ChartsRoute: typeof ChartsRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  ApiPublicHooksAutoDeclareResultsRoute: typeof ApiPublicHooksAutoDeclareResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/markets': {
      id: '/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-bets': {
      id: '/_authenticated/my-bets'
      path: '/my-bets'
      fullPath: '/my-bets'
      preLoaderRoute: typeof AuthenticatedMyBetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/results/history': {
      id: '/admin/results/history'
      path: '/results/history'
      fullPath: '/admin/results/history'
      preLoaderRoute: typeof AdminResultsHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results/declare': {
      id: '/admin/results/declare'
      path: '/results/declare'
      fullPath: '/admin/results/declare'
      preLoaderRoute: typeof AdminResultsDeclareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results/automation-runs': {
      id: '/admin/results/automation-runs'
      path: '/results/automation-runs'
      fullPath: '/admin/results/automation-runs'
      preLoaderRoute: typeof AdminResultsAutomationRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results/automation-audit': {
      id: '/admin/results/automation-audit'
      path: '/results/automation-audit'
      fullPath: '/admin/results/automation-audit'
      preLoaderRoute: typeof AdminResultsAutomationAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results/automation': {
      id: '/admin/results/automation'
      path: '/results/automation'
      fullPath: '/admin/results/automation'
      preLoaderRoute: typeof AdminResultsAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/bet/$marketId': {
      id: '/_authenticated/bet/$marketId'
      path: '/bet/$marketId'
      fullPath: '/bet/$marketId'
      preLoaderRoute: typeof AuthenticatedBetMarketIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/auto-declare-results': {
      id: '/api/public/hooks/auto-declare-results'
      path: '/api/public/hooks/auto-declare-results'
      fullPath: '/api/public/hooks/auto-declare-results'
      preLoaderRoute: typeof ApiPublicHooksAutoDeclareResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyBetsRoute: typeof AuthenticatedMyBetsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedBetMarketIdRoute: typeof AuthenticatedBetMarketIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyBetsRoute: AuthenticatedMyBetsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedBetMarketIdRoute: AuthenticatedBetMarketIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminResultsAutomationRoute: typeof AdminResultsAutomationRoute
  AdminResultsAutomationAuditRoute: typeof AdminResultsAutomationAuditRoute
  AdminResultsAutomationRunsRoute: typeof AdminResultsAutomationRunsRoute
  AdminResultsDeclareRoute: typeof AdminResultsDeclareRoute
  AdminResultsHistoryRoute: typeof AdminResultsHistoryRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepositsRoute: AdminDepositsRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminResultsAutomationRoute: AdminResultsAutomationRoute,
  AdminResultsAutomationAuditRoute: AdminResultsAutomationAuditRoute,
  AdminResultsAutomationRunsRoute: AdminResultsAutomationRunsRoute,
  AdminResultsDeclareRoute: AdminResultsDeclareRoute,
  AdminResultsHistoryRoute: AdminResultsHistoryRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ChartsRoute: ChartsRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  ApiPublicHooksAutoDeclareResultsRoute: ApiPublicHooksAutoDeclareResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
